# Generated by Django 3.0 on 2021-05-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField(unique=True)),
                ('numero_comprobante', models.CharField(max_length=20)),
                ('tipo_comprobante', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('debito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credito', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
